defaults:
    - /model: dummy_model
    - /optimizer: adam
    - /scheduler: on_plateau
    - _self_

# TARGET DOESN'T GO HERE, WE ARE NOT INSTATIATING THE MODULE DYNAMICALLY
pos_weight: 1
label_smoothing: 0.1
