scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: 'min'
    factor: 0.1
    patience: 10
    threshold: 1e-4
    min_lr: 1e-6

monitor: 'val/loss'
interval: 'epoch'
frequency: 1
