#TODO: change with the desired env name
name: ml_template
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults
dependencies:
    #TODO: edit with the dependencies you need
    - python=3.11
    - pip
    - pytorch>=2.5.1
    - torchvision>=0.20.1
    - torchaudio>=2.5.1
    - lightning

    # TODO: change with the desired CUDA version
    # CUDA is not allowed only on MACOS
    - pytorch-cuda=11.8

    - pandas
    - matplotlib
    - seaborn
    - jupyterlab
    - ipykernel
    - wandb
    - numpy
