#TODO: use the same env name specified in your environment.yaml file
CONDA_ENV_NAME = ml_template
#TODO: change the package name with your own
PYTHON_PACKAGE_PATH = src/ml_template
SRC_DIR = src
TEST_DIR = tests
#TODO: configure with your python version
PYTHON_VERSION = 3.11

# ENVIRONMENT MANAGEMENT ###############################################################################################

.PHONY: help install-env install-pack update-env remove-env

help:
	@echo "-------------------------------------------------------------------------"
	@echo "Makefile for $(CONDA_ENV_NAME)"
	@echo "-------------------------------------------------------------------------"
	@echo "Environment:"
	@echo "  install-env-cuda     Creates the Conda environment '$(CONDA_ENV_NAME)' (if it doesn't exist) from environment-cuda.yaml file."
	@echo "  install-env-cpu      Creates the Conda environment '$(CONDA_ENV_NAME)' (if it doesn't exist) from environment-cpu.yaml file."
	@echo "  install-pack-cuda    Makes sure that the environment is installed (uses the cpu configuration) and then tries to install the package in '$(PYTHON_PACKAGE_PATH)'."
	@echo "  install-pack-cpu     Makes sure that the environment is installed (uses the CUDA configuration) and then tries to install the package in '$(PYTHON_PACKAGE_PATH)'."
	@echo "  update-env-cuda      Updates the existing Conda environment with environment-cuda.yaml."
	@echo "  update-env-cpu       Updates the existing Conda environment with environment-cpu.yaml."
	@echo "  remove-env           Remove the '$(CONDA_ENV_NAME)' Conda environment."
	@echo ""
	@echo "Development and Testing:"
	@echo "  lint                 Executes linting and style controls (Ruff/Black/Flake8...)."
	@echo "  format               Applies code formating (Black/Ruff...)."
	@echo "  test                 Executes all tests with pytest."
	@echo "  test-cov             Exectues tests with pytest and shows the coverage report."
	@echo ""
	@echo "Main Execution (ML):"
	@echo "  predict              Executes the inference script (predict.py)."
	@echo "                       Use 'ARGS=\"<hydra_overrides>\"' to provide CLI arguments."
	@echo "                       Example: make predict ARGS=\"ckpt_path=path/to/model.ckpt\""
	@echo ""
	@echo "Cleaning:"
	@echo "  clean                Removes temporary Python files and test's cache."
	@echo "  clean-outputs        Removes the 'outputs/' directory generated by Hydra (WARNING!)."
	@echo "-------------------------------------------------------------------------"

install-pack-cuda:
	@make install-env-cuda
	@pip install -e .

install-pack-cpu:
	@make install-env-cpu
	@pip install -e .

install-env-cuda:
	@conda env list | grep -q "^$(CONDA_ENV_NAME)\s" || conda env create -f environment-cuda.yaml
	@make update-env-cuda

install-env-cpu:
	@conda env list | grep -q "^$(CONDA_ENV_NAME)\s" || conda env create -f environment-cpu.yaml
	@make update-env-cpu

update-env-cuda:
	@echo ">>> Updating the Conda environment '$(CONDA_ENV_NAME)'..."
	@conda env update -f environment-cuda.yaml --prune

update-env-cpu:
	@echo ">>> Updating the Conda environment '$(CONDA_ENV_NAME)'..."
	@conda env update -f environment-cpu.yaml --prune

remove-env:
	@echo ">>> Removing the '$(CONDA_ENV_NAME)' Conda environment"
	@conda deactivate || true 
	@conda env remove --name $(CONDA_ENV_NAME) -y

# DEV AND TESTING ######################################################################################################

.PHONY: lint format test test-cov

lint:
	@echo ">>> Executing linting (Ruff)"
	@conda run -n $(CONDA_ENV_NAME) ruff check $(SRC_DIR) $(TEST_DIR)
	@echo ">>> Checking code formatting (Black)"
	@conda run -n $(CONDA_ENV_NAME) black --check $(SRC_DIR) $(TEST_DIR)

format:
	@echo ">>> Code formatting (Ruff)"
	@conda run -n $(CONDA_ENV_NAME) ruff format $(SRC_DIR) $(TEST_DIR)
	@echo ">>> Code formatting (Black)"
	@conda run -n $(CONDA_ENV_NAME) black $(SRC_DIR) $(TEST_DIR)

test:
	@echo ">>> Executing Test (pytest)"
	@conda run -n $(CONDA_ENV_NAME) pytest $(TEST_DIR)

test-cov:
	@echo ">>> Executing Test with Coverage (pytest)..."
	@conda run -n $(CONDA_ENV_NAME) pytest --cov=$(SRC_DIR) --cov-report=term-missing $(TEST_DIR)


# MAIN EXECUTION #######################################################################################################

.PHONY: train predict

ARGS = ""

predict:
	@echo ">>> Executing Inference (predict.py)..."
	@conda run -n $(CONDA_ENV_NAME) python $(PYTHON_PACKAGE_PATH)/predict.py $(ARGS)


# CLEANING #############################################################################################################

.PHONY: clean clean-outputs

clean:
	@echo ">>> Removing temp Python files and cache..."
	@find . -type f -name "*.py[co]" -delete
	@find . -type d -name "__pycache__" -exec rm -rf {} +
	@find . -type d -name ".pytest_cache" -exec rm -rf {} +
	@rm -rf build/ dist/ *.egg-info/

clean-outputs:
	@echo ">>> WARNING: Removing directory 'outputs/'"
	@rm -rf outputs/

.DEFAULT_GOAL := help