defaults:
    - /dataset: dummy_dataset

train_val_test:
    - 0.8
    - 0.1
    - 0.1
batch_size: 2
num_workers: 1
pin_memory: True
persistent_workers: True,
train_data_augs_config:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: [7, 7]
        - _target_: torchvision.transforms.Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
eval_data_augs_config:
    _target_: torchvision.transforms.Compose
    transforms:
        - _target_: torchvision.transforms.Resize
          size: [7, 7]
        - _target_: torchvision.transforms.Normalize
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
random_seed: ${experiment.seed}
